### ISSUE TITLE
various issues noted by @ledgerwatch on DAO SLACK

### ISSUE THREAD

**Issue by usukan** [BitySA/whetcwithdraw#2]
https://thedao.slack.com/archives/child_dao_community/p1471863396001669

first comment: please use return values of 'send' function to make sure that events are not created if Ether is not sent. Later analysis based on events is easier than based on transactions, but events have to be reliable

if you use a recent version of Solidity compiler, it will give you warning if the results of send is not used

in the commonWithdraw function, please use curly braces after 'if' consistently throughout. Also, please use 'throw' consistently throughout instead of 'return'

and I would remove 'claimingRemaining' function, because escape hatch can achieve the same and even supersedes it

Also, I did not see any reentrancy protection, that needs to be clearly in sight

**Comment by BitySA** [comment]
Hello Usukan,

Thank you for reposting ledgerwatche's comments from the DAO Slack. We had already seen his comments and already addressed most of them in the latest commits.

>  please use return values of 'send' function to make sure that events are not created

Is already done.

> please use curly braces after 'if' consistently throughout.

Is also done

> Also, please use 'throw' consistently throughout instead of 'return'

This is not a matter of style but of functionality. If no state altering changes happen it should be fine to simply use `return`. This way you don't rob the user of all of the gas he is using for the transaction. If on the other hand you want to make sure that the entire transaction is rendered invalid then you should use `throw`.

> and I would remove 'claimingRemaining' function, because escape hatch can achieve the same and even supersedes it

You must have noticed that they have 2 different multisig addresses. The escape hatch  can be used at any point and will only serve as an emergency, while the remainingMultisig can only receive funds 6 months later. The same people will not be the owners of both the escape multisig and the remaining multisig.

For the escape hatch we may ask trusted people in the community to become signatories of that multisig. The reason is that the `escapeHatch` will function as a security switch of the contract but could also be misused and no single person or entity should have the power to control the funds in case such a thing happens.

> Also, I did not see any reentrancy protection, that needs to be clearly in sight

Could you specify in more detail what kind of protection you are looking for? Re-entrancy protection as in being careful about the order of accounting and sending out funds? Or something different?

**Comment by usukan** [comment]
ledgerwatch [9:23 AM]  
for the re-entrancy protection - in the 'commonWithdraw' function, one can specify the beneficiary address, which could be either an account address, or a contract. So when you send to a contract, it can potentially do things. Of course, if you use 'send', you do not give enough gas to the callee to make a re-enterant call. So, perhaps it is not an issue. Maybe they should just   add a comment explaining why the re-entrant call cannot happen

**Comment by BitySA** [comment]
Yes as ledgerwarch realized, `send()` prevents any reentrancy problems due to the gas stipend. Regardless a comment has been added. Thank you.
